# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - bicep/resourceGroups/pipeline/**

pool:
  vmImage: windows-latest

variables:
- group: resource-group-variables

steps:
- task: PowerShell@2
  displayName: login to azure
  inputs:
    targetType: 'inline'
    script: |
      az login --service-principal --username $(client_id) --password $(client_secret) --tenant $(tenant_id)
- task: PowerShell@2
  displayName: run bicep what-if
  inputs:
    targetType: 'inline'
    script: |
      cd ./bicep/resourceGroups/
      az deployment sub what-if --template-file .\deploy.bicep --parameters .\config\parameters.json -l australiaeast
