# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - bicep/resourceGroups/pipeline/**

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: run what-if
  inputs:
    targetType: 'inline'
    script: |
       az deployment sub what-if --template-file .\deploy.bicep --parameters .\config\parameters.json -l australiaeast
